program: run_sweep.py
method: bayes
project: price-forecasting
name: Level-2 models
metric:
  goal: maximize
  name: sharpe
parameters:
    directional_models_meta:
      value: True
    assets:
      value: ['daily_crypto']
    other_assets:
      value: ['daily_etf']
    exogenous_data:
      value: ['daily_glassnode']
    expanding_window_base:
      values: [True, False]
      distribution: categorical
    expanding_window_meta:
      values: [True, False]
      distribution: categorical
    n_features_to_select:
      values: [10, 20, 30]
      distribution: categorical
    dimensionality_reduction:
      value: True
    sliding_window_size_base: 
      values: [180, 280, 380]
      distribution: categorical
    sliding_window_size_meta: 
      values: [180, 280, 380]
      distribution: categorical
    retrain_every: 
      values: [10, 20, 30]
      distribution: categorical
    scaler:
      value: 'minmax'
    no_of_classes:
      values: ['two', 'three-balanced', 'three-imbalanced']
      distribution: categorical
    load_non_target_asset: 
      values: [True, False]
      distribution: categorical
    directional_models: 
      value: ["LogisticRegression_two_class", "LDA", "KNN", "CART", "NB", "AB", "RFC", "StaticMom"]
    meta_models: 
      values: ["LogisticRegression_two_class", "LDA", "KNN", "CART", "NB", "AB", "RFC"]
      distribution: categorical
    own_features:
      values: [['single_mom', 'date_days'], [], ['level_1', 'date_days'], ['date_days', 'level_2']]
      distribution: categorical
    other_features:
      values: [[], ['level_1']]
      distribution: categorical