program: run_sweep.py
method: grid
project: price-forecasting
name: Level-1 models
metric:
  goal: maximize
  name: sharpe
parameters:
    directional_models_meta:
      value: True
    assets:
      value: ['daily_crypto']
    other_assets:
      value: ['daily_etf']
    exogenous_data:
      value: ['daily_glassnode']
    expanding_window_base:
      values: [True, False]
      distribution: categorical
    expanding_window_meta:
      value: False
    n_features_to_select:
      value: 50
    dimensionality_reduction:
      value: True
    sliding_window_size_base: 
      value: 380
    sliding_window_size_meta: 
      value: 380
    retrain_every: 
      values: [10, 20, 30]
      distribution: categorical
    scaler:
      value: 'minmax'
    no_of_classes:
      value: 'two'
    load_non_target_asset: 
      value: True
    directional_models: 
      values: [['LogisticRegression_two_class'], ['SVC'], ['LDA'], ['KNN'], ['CART'], ['MNB'], ['NB'], ['AB'], ['RFC'], ['XGB_two_class'], ['LGBM']]
      distribution: categorical
    meta_models: 
      value: ["LGBM", "LogisticRegression_two_class"]
    own_features:
      value: ['date_days', 'level_2', 'lags_up_to_5']
    other_features:
      value: ['level_2', 'lags_up_to_5']
    exogenous_features:
      value: ['z_score']