program: run_sweep.py
method: grid
project: price-forecasting
name: Meta labelling
metric:
  goal: maximize
  name: sharpe
parameters:
    assets:
      value: ['daily_crypto']
    other_assets:
      value: ['daily_etf']
    exogenous_data:
      value: ['daily_glassnode']
    sliding_window_size: 
      value: 380
      distribution: categorical
    n_features_to_select:
      values: [40, 50, 60]
      distribution: categorical
    dimensionality_reduction_ratio:
      value: 0.5
    retrain_every: 
      value: 20
    scaler:
      value: 'minmax'
    no_of_classes:
      value: 'two'
    load_non_target_asset: 
      value: True
    directional_models: 
      distribution: categorical
      values:
      - ["LDA", "LogisticRegression_two_class", "KNN", "SVC", "CART", "NB", "AB", "RFC", "XGB_two_class", "LGBM", "StaticMom"]
      - ["LogisticRegression_two_class", "LDA", "NB", "RFC", "XGB_two_class", "LGBM", "StaticMom"]
      - ["LogisticRegression_two_class", "LDA", "LGBM", "RFC", "XGB_two_class"]
    meta_models: 
      value: ["LGBM", "LogisticRegression_two_class"]
    own_features:
      value: ['date_days', 'level_2', 'lags_up_to_5']
    other_features:
      value: ['level_2', 'lags_up_to_5']
    exogenous_features:
      value: ['z_score']
